<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LicenciaSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $licencias = [
            [
                'id' => 1,
                'plan_id' => null,
                'nombre' => 'Básico Mensual',
                'tipo' => 'MENSUAL',
                'max_restaurantes' => 1,
                'max_usuarios' => 15,
                'precio' => 299.00,
                'precio_anual' => 3588.00,
                'paypal_plan_id' => null,
                'activo' => 1,
                'dias_prueba' => 0,
                'es_personalizado' => 0,
                'configuracion' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'plan_id' => null,
                'nombre' => 'Premium Mensual',
                'tipo' => 'MENSUAL',
                'max_restaurantes' => 2,
                'max_usuarios' => 30,
                'precio' => 499.00,
                'precio_anual' => 5988.00,
                'paypal_plan_id' => null,
                'activo' => 1,
                'dias_prueba' => 0,
                'es_personalizado' => 0,
                'configuracion' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'plan_id' => null,
                'nombre' => 'Básico Anual',
                'tipo' => 'ANUAL',
                'max_restaurantes' => 1,
                'max_usuarios' => 15,
                'precio' => 2999.00,
                'precio_anual' => 2999.00,
                'paypal_plan_id' => null,
                'activo' => 1,
                'dias_prueba' => 0,
                'es_personalizado' => 0,
                'configuracion' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'plan_id' => null,
                'nombre' => 'Premium Anual',
                'tipo' => 'ANUAL',
                'max_restaurantes' => 2,
                'max_usuarios' => 30,
                'precio' => 4999.00,
                'precio_anual' => 4999.00,
                'paypal_plan_id' => null,
                'activo' => 1,
                'dias_prueba' => 0,
                'es_personalizado' => 0,
                'configuracion' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'plan_id' => null,
                'nombre' => 'Crecimiento Mensual',
                'tipo' => 'MENSUAL',
                'max_restaurantes' => 3,
                'max_usuarios' => 45,
                'precio' => 2399.00,
                'precio_anual' => 28788.00,
                'paypal_plan_id' => null,
                'activo' => 1,
                'dias_prueba' => 0,
                'es_personalizado' => 0,
                'configuracion' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'plan_id' => null,
                'nombre' => 'Crecimiento Anual',
                'tipo' => 'ANUAL',
                'max_restaurantes' => 3,
                'max_usuarios' => 45,
                'precio' => 25899.00,
                'precio_anual' => 25899.00,
                'paypal_plan_id' => null,
                'activo' => 1,
                'dias_prueba' => 0,
                'es_personalizado' => 0,
                'configuracion' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'plan_id' => null,
                'nombre' => 'Pro Mensual',
                'tipo' => 'MENSUAL',
                'max_restaurantes' => 6,
                'max_usuarios' => 100,
                'precio' => 4199.00,
                'precio_anual' => 50388.00,
                'paypal_plan_id' => null,
                'activo' => 1,
                'dias_prueba' => 0,
                'es_personalizado' => 0,
                'configuracion' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'plan_id' => null,
                'nombre' => 'Pro Anual',
                'tipo' => 'ANUAL',
                'max_restaurantes' => 6,
                'max_usuarios' => 100,
                'precio' => 45349.00,
                'precio_anual' => 45349.00,
                'paypal_plan_id' => null,
                'activo' => 1,
                'dias_prueba' => 0,
                'es_personalizado' => 0,
                'configuracion' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'plan_id' => null,
                'nombre' => 'Prueba 30 días',
                'tipo' => 'PRUEBA',
                'max_restaurantes' => 1,
                'max_usuarios' => 5,
                'precio' => 0.00,
                'precio_anual' => 0.00,
                'paypal_plan_id' => null,
                'activo' => 1,
                'dias_prueba' => 30,
                'es_personalizado' => 0,
                'configuracion' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'plan_id' => null,
                'nombre' => 'Enterprise',
                'tipo' => 'EMPRESA',
                'max_restaurantes' => null,
                'max_usuarios' => null,
                'precio' => null,
                'precio_anual' => null,
                'paypal_plan_id' => null,
                'activo' => 1,
                'dias_prueba' => 0,
                'es_personalizado' => 1,
                'configuracion' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
        ];

        foreach ($licencias as $licencia) {
            DB::table('licencias')->updateOrInsert(
                ['id' => $licencia['id']],
                $licencia
            );
        }
    }
}